import React from 'react';

export const metadata = {
  title: 'About Cart',
  description: 'Generated by create next app',
};
const About = () => {
  return <div>Cart Page</div>;
};

export default About;
