import React from 'react'

type Props = {}
export const metadata = {
  title: 'About Cart',
  description: 'Generated by create next app',
}
const About = (props: Props) => {
  return (
    <div>Cart Page</div>
  )
}

export default About