import React from 'react'
import Content from './content'

type Props = {}
export const metadata = {
  title: 'Analytics',
  description: 'Generated by create next app',
}
const Home = (props: Props) => {
  return (
    <div>
      <h1>Home Analytics</h1>
      <Content />
    </div>
  )
}

export default Home