'use client';
import Link from 'next/link';
import './globals.css';
import { Inter } from 'next/font/google';
import { usePathname } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout(props: { children: React.ReactNode }) {
  const menu = [
    {
      name: 'Home',
      title: 'Root app',
      href: '/',
    },
    {
      name: 'Dashboard',
      href: '/dashboard',
    },
    {
      name: 'Product',
      href: '/product',
      title: 'dynamic routes',
    },
    {
      name: 'Shop',
      href: '/shop',
    },
    {
      name: 'Optional',
      href: '/optional',
      title: 'dynamic routes',
    },
    {
      name: 'Parallel',
      href: '/parallel_test',
    },
    {
      name: 'Feed',
      href: '/feed',
      title: 'Incepting routes, parallel',
    },
  ];
  const pathname = usePathname();
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={inter.className}>
        {' '}
        <header className="flex justify-between bg-black p-4 text-white font-bold">
          <Link href="/">Header RootLayout</Link>
        </header>
        <nav className="flex flex-wrap">
          {menu.map((link) => {
            const isActive = link.href.length > 2 ? pathname.includes(link.href) : pathname === link.href;
            return (
              <Link
                className={`p-2 rounded-md flex flex-col items-center justify-center bg-black m-2 shadow-sm ${
                  isActive ? 'text-black border-2 border-black bg-gray-200' : 'text-white'
                }`}
                href={link.href}
                key={link.name}
              >
                <h1>{link.name}</h1>
                <h2>{link.title}</h2>
              </Link>
            );
          })}
        </nav>
        {props.children}
      </body>
    </html>
  );
}
