export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout(props: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <div>
      {props.children}
      {props.modal}
    </div>
  );
}
