'use client'
import { usePathname } from 'next/navigation'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout(props: {
  children: React.ReactNode
  modal: React.ReactNode
}) {
    const pathname = usePathname()
  return (
    <div>
      {props.children}
      {props.modal}
      </div>
  )
}
