import Button from '@/components/atoms/Button';
import React from 'react';

export const metadata = {
  title: 'About Page',
  description: 'Generated by create next app',
};
const About = () => {
  return (
    <div>
      About Page
      <Button kind='primary'>Lê Trunks</Button>
    </div>
  );
};

export default About;
