'use client';
import React from 'react';

export const metadata = {
  title: 'About Accout',
  description: 'Generated by create next app',
};
const About = () => {
  return <div>Account Page</div>;
};

export default About;
