import React from 'react'

type Props = {}
export const metadata = {
  title: 'About Accout',
  description: 'Generated by create next app',
}
const About = (props: Props) => {
  return (
    <div>Account  Page</div>
  )
}

export default About