import React from 'react'

type Props = {}
export const metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
}
const Home = (props: Props) => {
  return (
    <div>Home Page</div>
  )
}

export default Home