import React from 'react';

export const metadata = {
  title: 'Contact Page',
  description: 'Generated by create next app',
};
const Home = () => {
  return <div>Contact Page</div>;
};

export default Home;
